#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo"
    echo "sudo $0 $*"
    exit 1
fi

SSID=$1

WPA_PASS=$(wpa_passphrase $1 $2 | awk -F= '{print $2}' | awk 'NR==4')


printf "Interface=wlp2s0
Connection=wireless
Security=wpaESSID='$SSID'
IP=dhcp
Key=\\\\\"$WPA_PASS
TimeoutDHCP=20
" > /etc/netctl/wlp2s0-$SSID
systemctl stop NetworkManager
systemctl restart netctl
systemctl start netctl-auto@wlp2s0
ping 8.8.8.8
